language: node_js
node_js:
- node
- '8'
- '7'
- '6'
- '5'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- echo "Running tests against $(node -v) ..."
- npm test
jobs:
  include:
  - stage: publish
    install: skip
    script: skip
    deploy:
      provider: npm
      email: jsachs8@gmail.com
      api_key:
        secure: KZaijSz7F3i/k6+uLUrAwTOAPqXWrSF2bQJvbNs+LzVAYoa83NZ0iO/bfy0mWt/YjozLP86nY666cP2X5i0n5gsfuzVmuyFwiOV26U3Rrjd9ORAbXT//JntntHTM0243GRmj2f/TuhYNykZZTXPKkFPNMZ5qiGxnXRjaWa6c6Ckwx/iM8R2Bh/mL8vpVmStpXVwTa++fKD0SOxh1K5xrwheNe73S5CB0+mU7sz34+q6ZiJ1bWDMRXKkldqBxFICnaqbCV2Etw+/6iDaGmrAEfiHGgg7OW0eaIvtlL/sTIAY75k52Ll+kDGsoifEARXc+J8RmIzl72PQ4jJLC3HwC4SuXw1rOlZwJOcxVGW3hEsdmQFHMykxrzzSosRHj3QWXEJfcoJfsAKgYm8plPiq50MdwExlrw5PlYjY8H344nZV3/ds5QlteN+dkzKmBZaoSKpCtn4khxyWKe1Rh7vxGmghiy6yvXT65Pzp0jr/+js8BHE+A1EMnzm+M4baFhsoOK3L3UYzTZlWfVys/MZMfje+l8w6NTmQagkgyL3bCBuxlHSJMnSS+oXfjusiU+lvspjn6qkSfsuJtTtt+YSwhiduhlLsjHaociBeDP+oXkazcouTXjSt/44im6qq0iZ4rwrueNEbdtF2UbYEWX0jvgdwKO113oOwbS+zs2Bo1Ksw=
      on:
        branch: master
