language: node_js
node_js:
- node
- '8'
- '7'
- '6'
- '5'
cache:
  directories:
  - node_modules
install:
- npm install
script:
- echo "Running tests against $(node -v) ..."
- npm test
jobs:
  include:
    - stage: publish
      install: skip
      script: skip
      deploy:
        provider: npm
        email: "jsachs8@gmail.com"
        api_key:
          secure: t1/Uwbg8sM8stttiXF9u82uUxY4a9aZKTYITVnZVC+zwbX85xfN4HePn+6g5XtEfeSmLs5OXkFnBnWLi6UDXJz9W15F1RbbBAspbZ0zAQ/mhpEdWCStV6XI/Jxf/ege6IUILt6PB9jjNAGthIQxTar7ldJJ3bPaUHhzU5Lo+rt8V7d7q4+pJyqNM/4olD/PI6RWrj3fyh9WRwhbHwqzs6rF9DxR6zMgBFN5oX08eYY1jRv0I7gadiD0nvEAItryL0dLDlLyHHIyn0qEp/jnp7fPUu0+VzZgCMoZVxHYMjrBTdBLoD6XaIDI3X+4RzCcTUdbdBGrJIDL2vmzsihKXxF/z6KvEXQqYVLp6HNg6ns9aD49/vDKLP0mtq0cLzd74WPtXPU95g7tL35W2akVPWX85hfG3NYmsiq+fHnPfPJMPtFUv+pwrPjpcmE20+9qCmojMuuZPRXmcSdsWzCD9yUYLTtuUVKSABO6WTtBH2edxQAWy/7WXGEN6asHwtvHihh7pbG7Jk3iz+l3qRO590IEMp3XmL9+n9OyDU7gOeOKvPgwpqw4wWNYd6BPAFh+KeM1cevVU9UUoNZcLcF3M7OntXfKlKmC1ND4uvEmhAV/C11rOh3xOxhjq2BEbv2XtTE3y4ZWPGRwGovESDN/IqyramLyrfMeP+ElJdWKx92c=
        on:
          branch: master
